# Generated by Django 5.0 on 2025-05-10 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='description',
            new_name='custom_description',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='name',
            new_name='custom_name',
        ),
    ]
