# Generated by Django 5.0 on 2025-05-10 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_description_homepage_custom_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='custom_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='custom_name',
            new_name='name',
        ),
    ]
