# Generated by Django 5.0 on 2025-05-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_custom_description_homepage_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presidentmessage',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
