# Generated by Django 5.0 on 2025-05-16 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventspage',
            name='long_description',
            field=models.TextField(blank=True, help_text='Detailed description of the event', null=True),
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.eventspage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
