# Generated by Django 5.0 on 2025-05-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_eventspage_long_description_eventimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberspage',
            options={'ordering': ['society_designation', 'member_name'], 'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.AddField(
            model_name='memberspage',
            name='date_of_joining',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='memberspage',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberspage',
            name='society_designation',
            field=models.CharField(choices=[('PRESIDENT', 'President'), ('VICE_PRESIDENT', 'Vice President'), ('GENERAL_SECRETARY', 'General Secretary'), ('SECRETARY', 'Secretary'), ('TREASURER', 'Treasurer'), ('EXECUTIVE_MEMBER', 'Executive Member'), ('GENERAL_MEMBER', 'General Member')], default='GENERAL_MEMBER', max_length=50),
        ),
        migrations.AlterField(
            model_name='memberspage',
            name='member_position',
            field=models.CharField(help_text='Academic/Professional position', max_length=200),
        ),
    ]
