# Generated by Django 5.0 on 2025-05-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_memberspage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberspage',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True),
        ),
    ]
