# Generated by Django 5.0 on 2025-05-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_memberspage_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberspage',
            name='member_bio',
            field=models.TextField(default=None, null=True),
        ),
    ]
