# Generated by Django 5.0 on 2025-05-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_memberspage_member_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerypage',
            name='category',
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='caption',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
