# Generated by Django 5.0 on 2025-05-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_gallerypage_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerypage',
            options={'ordering': ['-id'], 'verbose_name': 'Gallery Image', 'verbose_name_plural': 'Gallery Images'},
        ),
        migrations.RemoveField(
            model_name='gallerypage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='gallerypage',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='gallerypage',
            name='title',
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='caption',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
