# Generated by Django 5.0 on 2025-05-16 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_gallerypage_options_remove_gallerypage_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='map_embed_code',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='title',
        ),
    ]
